version : 1
formatters :
 brief :
  format : "%(asctime)s - %(message)s"
 simple :
  format : "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  datefmt : "%Y/%m/%d %H:%M:%S"
handlers :
 console :
  class : logging.StreamHandler
  formatter : brief
  level : INFO
  stream : ext://sys.stdout
 file :
  class : logging.FileHandler
  formatter : simple
  level : DEBUG
  filename : debug.log
  encoding : utf8
 error :
  class : logging.handlers.RotatingFileHandler
  formatter : simple
  level : ERROR
  filename : error.log
  maxBytes : 10485760
  backupCount : 20
  encoding : utf8
loggers :
 mylogger :
  level : DEBUG
  handlers : [console,file,error]
root :
 level : ERROR
 handlers : [console]